from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Pre-fill an operation-intent production decision memo draft JSON "
            "from a rollout bundle generated by build_operation_intent_rollout_bundle.py."
        )
    )
    parser.add_argument(
        "--bundle",
        required=True,
        help="Path to rollout bundle JSON",
    )
    parser.add_argument(
        "--environment-scope",
        default="staging-canary",
        help="Environment scope label for the memo draft",
    )
    parser.add_argument(
        "--decision-owner",
        default="",
        help="Optional decision owner identifier",
    )
    parser.add_argument(
        "--output",
        default="",
        help="Optional output path for draft JSON",
    )
    return parser.parse_args()


def _safe_float(value: object) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _safe_int(value: object) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def _load_bundle(path: Path) -> dict[str, object]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError("Bundle file is not a JSON object")
    return payload


def _auto_result(flag: bool) -> str:
    return "pass_candidate" if flag else "fail_candidate"


def _build_memo_draft(
    bundle: dict[str, object],
    bundle_path: Path,
    environment_scope: str,
    decision_owner: str,
) -> dict[str, object]:
    aggregate = bundle.get("aggregate", {})
    threshold_checks = bundle.get("threshold_checks", {})

    query_share_window_pass = bool(threshold_checks.get("query_share_window_pass", False))
    overall_query_share_percent = _safe_float(aggregate.get("overall_query_share_percent", 0.0))
    days_below_threshold = _safe_int(aggregate.get("days_below_threshold", 0))
    total_query_rejected_strict_delta = _safe_int(aggregate.get("total_query_rejected_strict_delta", 0))
    max_mismatch_rate = _safe_float(aggregate.get("max_mismatch_rate_per_minute", 0.0))

    strict_rejection_auto_pass = total_query_rejected_strict_delta == 0

    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "source_bundle": str(bundle_path).replace("\\", "/"),
        "decision_summary": {
            "decision_date": "",
            "environment_scope": environment_scope,
            "proposed_action": "undetermined",
            "decision_owner": decision_owner,
        },
        "evidence_inputs": {
            "rollout_bundle_file": str(bundle_path).replace("\\", "/"),
            "strict_mode_sunset_test_log": "",
            "error_rate_comparison_report": "",
            "client_compatibility_signoff_record": "",
        },
        "threshold_evaluation": {
            "query_share_threshold": {
                "rule": "query transport share below 1% for 14 consecutive days",
                "overall_query_share_percent": round(overall_query_share_percent, 4),
                "days_below_threshold": days_below_threshold,
                "query_share_window_pass": query_share_window_pass,
                "auto_result": _auto_result(query_share_window_pass),
            },
            "strict_rejection_stability": {
                "rule": "query_rejected_strict remains near zero outside strict-mode windows",
                "total_query_rejected_strict_delta": total_query_rejected_strict_delta,
                "strict_mode_window_periods_reviewed": "",
                "auto_result": _auto_result(strict_rejection_auto_pass),
            },
            "mismatch_stability": {
                "rule": "mismatch does not show sustained increase versus baseline",
                "max_mismatch_rate_per_minute": round(max_mismatch_rate, 4),
                "baseline_mismatch_rate_per_minute": "",
                "sustained_duration_observed": "",
                "auto_result": "review_required",
            },
            "error_rate_safety": {
                "rule": "no material 400/401 regression attributable to migration",
                "baseline_400_401_rates": "",
                "canary_400_401_rates": "",
                "auto_result": "review_required",
            },
            "client_regression_gate": {
                "rule": "no unresolved P1/P2 regressions in start/stop intent flow",
                "open_p1_count": "",
                "open_p2_count": "",
                "auto_result": "review_required",
            },
        },
        "rollback_trigger_review": {
            "header_401_rate_exceeded_2x_for_30m": "",
            "mismatch_threshold_exceeded_for_30m": "",
            "critical_compatibility_cohort_blocked": "",
            "incident_ids_and_remediation": "",
        },
        "final_recommendation": {
            "recommended_action": "undetermined",
            "rationale_summary": "",
            "required_followups_before_production": "",
        },
        "approvals": {
            "backend_owner": "",
            "client_owner": "",
            "qa_owner": "",
            "operations_owner": "",
            "final_approver": "",
        },
    }


def main() -> int:
    args = _parse_args()
    bundle_path = Path(args.bundle)
    if not bundle_path.exists():
        raise RuntimeError(f"Bundle file does not exist: {bundle_path}")

    bundle = _load_bundle(bundle_path)
    memo = _build_memo_draft(
        bundle=bundle,
        bundle_path=bundle_path,
        environment_scope=args.environment_scope,
        decision_owner=args.decision_owner,
    )

    text = json.dumps(memo, indent=2, sort_keys=True)
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(text + "\n", encoding="utf-8")

    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())